import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from './../components/layout/Layout';
import {
	Button,
	ButtonGroup,
	Flex,
	Heading,
	Highlight,
	Stack,
	Text
} from '@chakra-ui/react';

const Home: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>Ticket App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Stack h="100vh"
				w='100%'
				backgroundImage="linear-gradient(rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.5)), url(https://app.fanz.events/home/top_background.jpg)"
				backgroundSize="cover"
				m="0"
				flexDir="row"
			>
				<Stack w="50%" h="100%" flexDir={"row"} alignItems={'center'} p="60px">
					<Flex flexDir={"column"}>
						<Heading lineHeight='150%'
							size='2xl'
						>
							<Highlight
								query="NFTs."
								styles={{ px: '4', py: '1', rounded: 'full', bg: 'rgba(0, 255, 255, 0.8)' }}
							>
								Descubrí eventos, Creá propios y Vendé tickets como NFTs.
							</Highlight>
						</Heading>
						<Text fontSize="xl" as='b'>En la primera plataforma de venta de entradas descentralizada del mundo</Text>
						<Flex flexDir={"row"} w="100%" mt="15px">
							<ButtonGroup variant='solid' spacing='9'>
								<Button colorScheme='blue' size="lg">EXPLORAR EVENTOS</Button>
								<Button color="#1C74CB" border='1px' borderColor='#1C74CB' size="lg">CREAR EVENTOS</Button>
							</ButtonGroup>
						</Flex>
					</Flex>
				</Stack>
				<Stack w="50%" h="100%" flexDir={"row"} alignItems={'center'}>

				</Stack>
			</Stack>
		</Layout>


	)
}

export default Home